### ISSUE TITLE
Eliminate unnecessary dependencies

### ISSUE THREAD

**Issue by godber** [planetarypy/pdsview#14]
Do we really need AstroPy and Pyfits?  Can these dependencies be eliminated?  Maybe not.  If not, then we should make it open Fits files too.

**Comment by nikhilkalige** [comment]
Removed pyfits.. using astropy only

**Comment by godber** [comment]
@bvnayak any idea whether PyFITS was really needed?  It's been removed for now at least.

**Comment by bvnayak** [comment]
No idea for PyFITS. I think its okay to remove `pyfits` for now. I will check it during my GUI development stage and will add it only if its been used somewhere.
