### ISSUE TITLE
Fix Python version compatibility - add 2.6 and 3.4

### ISSUE THREAD

**Issue by godber** [planetarypy/pdsview#18]
We need to maintain compatibility with Python 2.6 and 3.4 (and 3.3, but at lower priority).  This means, first and foremost that the code should run in these environments.  Second that both tox and travis are configured to test these environments.  This is a bit messy for this package because it has low level dependencies that we resolve with conda in travis.  It's still achievable.

**Comment by percurnicus** [comment]
pdsview has 3.4 compatibility in https://github.com/planetarypy/pdsview/pull/21. Due to constraints in Travis/PySide this cannot be tested in Travis. However, tests pass on make test-all/tox so there is 3.4 compatibility. Ginga does not have 2.6 compatibility so 2.6 compatibility is not possible

**Comment by godber** [comment]
Great!
