### ISSUE TITLE
Think about utilizing Glue

### ISSUE THREAD

**Issue by percurnicus** [planetarypy/pdsview#32]
Glue may be able to handle multispectral and pds files with multiple images better than we are handling them now: http://www.glueviz.org/en/stable/index.html

**Comment by percurnicus** [comment]
Useful links for utilizing histogram:
http://www.glueviz.org/en/stable/python_guide/data_viewer_options.html
http://www.glueviz.org/en/stable/python_guide/data_viewer_options.html

**Comment by cmillion** [comment]
FWIW: I spent some time earlier this year trying to use Glue to work with multi-spectral Pancam data. It functioned, but just sort of barely. It's not really optimized for working with tens of millions of data points (e.g. seven filters + PCA output). I also find the interface to be incredibly clunky in other ways, like just the sheer number of clicks required to do basic things like plot one column against another. We ultimately decided, for that project, that it would just be easier to write our own lightweight tools to analyze the data.

Caveat: We did not try to do any scripting in Glue, like the histogram examples to which you link. Maybe it works better if you do it that way.

**Comment by percurnicus** [comment]
Good to know so I don't waste my time coming to the same conclusion haha. After reading through Glue documentation more I realized that any sort of integration would be more general (hence the name change to this issue). PDSView needs a histogram viewer alongside the image and I like how interactive Glue's histograms are. The data linking might also be useful but I think it would be better to make our own method within ImageSet to do something similar
