### ISSUE TITLE
Why not qtpy?

### ISSUE THREAD

**Issue by percurnicus** [planetarypy/pdsview#40]
@godber why don't we use qtpy? I'm guessing its a licensing issue but I'm not sure and I don't know enough about licensing. I feel like it would fix our dependency problems and make our lives easier.

**Comment by godber** [comment]
I don't believe I was aware of it when we started this.  I think I have a vague note somewhere like "Don't forget about qtpy."  I consider pdsview yours so you should proceed how you see fit.  It's licensed MIT which is super permissive, so thats no barrier.

**Comment by percurnicus** [comment]
More for future me: follow Glue's setup: http://glueviz.org/en/stable/installation.html#installing-with-pip
