### ISSUE TITLE
Add "Histogram" tool in pdsview.

### ISSUE THREAD

**Issue by bvnayak** [planetarypy/pdsview#5]
Ginga has a very good widget for `Histogram.py` which can be used to add histogram support tool in our image viewer or we can make our own by taking its reference.  I have modified some of the histogram tool utilities like line color, grid off, plot style etc. in the conda env 'ginga27' and 'ginga34' on my PC.

**Comment by bvnayak** [comment]
![screen shot 2015-05-13 at 2 20 07 pm](https://cloud.githubusercontent.com/assets/11728474/7621371/31a234b0-f97b-11e4-8317-e61bada21bb9.png)

**Comment by percurnicus** [comment]
I'm starting to address this issue. I like ginga's ``Histogram.py`` but not sure about embedding the entire plugin into the the main widget and then maintaining the cuts for the different channels. I'm going to try following this example: https://github.com/sir-wiggles/pyStocker/blob/master/utils.py#L174 and using these modules from matplotlib: http://matplotlib.org/api/backend_qt4agg_api.html, http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.axvline.html, http://matplotlib.org/users/event_handling.html
