### ISSUE TITLE
Add "Channel Next" (Ch +) and "Channel Prev" (Ch -) button in pdsview

### ISSUE THREAD

**Issue by bvnayak** [planetarypy/pdsview#6]
Add these two buttons for an RGB image. Also, modify the "Histogram tool" too show histogram of each plane i.e. R, G and B separately.

**Comment by bvnayak** [comment]
![screen shot 2015-05-13 at 2 22 43 pm](https://cloud.githubusercontent.com/assets/11728474/7621417/8c0a5086-f97b-11e4-9e1a-400bed77c435.png)

**Comment by bvnayak** [comment]
We can clearly see the 3 histograms for R, G, B in a single frame. Make it separated. By doing this, we will also have to add a button "RGB" which will enable the RGB mode for an image to display.

**Comment by percurnicus** [comment]
Fixed in #28 
![screen shot 2015-08-31 at 1 39 35 pm](https://cloud.githubusercontent.com/assets/12278722/9589882/1df82778-4fe6-11e5-8b1e-262e48e3586d.png)
